from __future__ import annotations

import re


CODE_FILE_EXTENSIONS = (
    ".py",
    ".js",
    ".ts",
    ".tsx",
    ".jsx",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".rb",
    ".php",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".cxx",
    ".hh",
    ".hpp",
    ".hxx",
    ".cs",
    ".swift",
    ".scala",
    ".sh",
    ".bash",
    ".zsh",
    ".fish",
    ".ps1",
    ".psm1",
    ".psd1",
    ".bat",
    ".cmd",
    ".pl",
    ".pm",
    ".lua",
    ".r",
    ".jl",
    ".sql",
)

CODE_LANGUAGE_HINTS = (
    "code",
    "codice",
    "python",
    "javascript",
    "typescript",
    "java",
    "go",
    "rust",
    "c",
    "c++",
    "cpp",
    "csharp",
    "c#",
    "powershell",
    "shell",
    "bash",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "scala",
    "lua",
    "sql",
)

CODE_REVIEW_REQUEST_HINTS = (
    "find bugs",
    "find bug",
    "review",
    "inspect",
    "issues",
    "issue",
    "risks",
    "risk",
    "bug",
    "bugs",
    "vulnerability",
    "vulnerabilities",
    "vuln",
    "vulns",
    "security",
    "insecure",
    "exploit",
    "exploitable",
    "cve",
    "injection",
    "xss",
    "csrf",
    "rce",
    "traversal",
    "auth bypass",
    "trovi bug",
    "trova bug",
    "rivedi",
    "analizza",
    "problemi",
    "rischi",
    "vulnerabilità",
    "vulnerabilita",
    "vulnerabile",
    "sicurezza",
    "insicuro",
    "falla",
    "falle",
)

CODE_REVIEW_OUTPUT_HINTS = (
    "bug",
    "bugs",
    "risk",
    "risks",
    "issue",
    "issues",
    "finding",
    "findings",
    "weakness",
    "weaknesses",
    "regression",
    "regressions",
    "vulnerability",
    "vulnerabilities",
    "vuln",
    "vulns",
    "security",
    "insecure",
    "exploit",
    "exploitable",
    "cve",
    "no clear bug",
    "no concrete bug",
    "no clear vulnerability",
    "no concrete vulnerability",
    "nessun bug",
    "nessun problema",
    "nessuna vulnerabilità",
    "nessuna vulnerabilita",
    "rischio",
    "rischi",
    "problema",
    "problemi",
    "vulnerabilità",
    "vulnerabilita",
    "sicurezza",
)


def has_code_language_hint(text: str) -> bool:
    for hint in CODE_LANGUAGE_HINTS:
        if hint in {"c++", "c#"}:
            if hint in text:
                return True
            continue
        if re.search(rf"\b{re.escape(hint)}\b", text):
            return True
    return False


def has_code_file_extension(text: str) -> bool:
    return any(ext in text for ext in CODE_FILE_EXTENSIONS)
